### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by ashbc** [ashbc/tgrsite#16]

**Comment by finnbar** [comment]
From discussion we've had, the following is actionable. We will create the notifications as a separate app which has the model Notification consisting of a user that owns it (Foreign Key), its type (likely enum, e.g. from Newsletters, Messages etc.), content and date. We aim to only keep the most recent n notifications (something like 50), which can be done easily via checking the number of notifications when adding one (or Django might just do this for us!). Our API consists of getNotifications(), getNotificationsCount() and notify() or something like that.

Notifications should come from:
* When a newsletter is published.
* When someone joins an event that you are running, OR everyone in that event gets said notification if nobody is running it.
* Reply to a forum post you're in.
* [FUTURE] at mentions in text.
* When you get a message.

**Comment by finnbar** [comment]
Implemented in the notifications branch.

**Comment by finnbar** [comment]
We did it reddit :small_red_triangle:
