### ISSUE TITLE
Newlines being removed from forum posts

### ISSUE THREAD

**Issue by ashbc** [ashbc/tgrsite#55]
potentially related to editing posts? CNR for now.

**Comment by ashbc** [comment]
Known information:

- The model uses a CharField rather than a TextField for the text
- Subsequently the admin site defaults to a single-line text input rather than a textarea
- Only been observed so far in initial thread posts, not responses

**Comment by ashbc** [comment]
Editing users on the admin site, in order to add to groups, also removes newlines from bios.

**Comment by finnbar** [comment]
Doesn't seem to have come up recently.
