### ISSUE TITLE
NEWSLETTERS TWO POINT OH

### ISSUE THREAD

**Issue by finnbar** [ashbc/tgrsite#75]
In my grand attempt to unify the three versions of the newsletter into one remotely pretty version of the newsletter, the new Newsletter app must be created. (Being the Newsletter Tsar has its benefits, huh)

- [x] Creation of Newsletter model.
- [x] Ability to list Newsletters.
- [x] Ability to create Newsletters.
- [x] Ability to view Newsletters.
- [x] Ability to *edit* Newsletters.
- [x] Ability to go between pages (list, detail and create).
- [x] Make pages pretty. Includes Quality of Life stuff such as linking to old forum with old newsletters in, because reimporting them is too much effort.
- [x] Add Newsletters to topbar.
- [x] Publishing tools (can keep a draft).
- [x] Markdown editor. (done in simplemde branch, needs to be checked, safely merged and deployed)

All work on this is in the newsletters branch.

**Comment by ashbc** [comment]
Sounds good

**Comment by finnbar** [comment]
Done on Newsletters branch, should probably be checked.
