### ISSUE TITLE
Callum's suggestions from exec chat

### ISSUE THREAD

**Issue by finnbar** [ashbc/tgrsite#84]
Quote:

Looking good! I know it's a bit late now, but I had meant to mention some other stuff I think might be worth updating again.
I'm still lacking the power to mark other people's games as "finished" or outright delete, which might be nice for keeping events a little more tidy
And it might just be me, but I think having the events guide, filter options, show past games, create event etc. at the top of the page rather than the bottom, idk?

Actionable:

Move "create game" etc up to top (even if only temporary), look into Callum's permissions.

**Comment by ashbc** [comment]
Re: marking games as "finished" - this is doable via the admin site for anyone with the permission to change rpgs. I've added Callum to a group with those permissions. Increasing admin UI functionality on-site is planned but low priority.

Re: moving stuff - this would be less of an issue if/when we sort out pagination, but it's still probably a good idea to move up.

**Comment by finnbar** [comment]
Change for latter in fixes branch, will have to talk to Callum at some point about former.
