### ISSUE TITLE
Questionable code mail_managers

### ISSUE THREAD

**Issue by finnbar** [ashbc/tgrsite#85]
We should probably check this, `mail_managers` isn't imported in the file containing: https://github.com/ashbc/tgrsite/blob/b9aa985d143dfc5d8d4736187131ad974ed1a7ef/users/views.py#L151.

**Comment by ashbc** [comment]
Proposed fix: import `django.core.mail.mail_managers` in file.
https://docs.djangoproject.com/en/2.1/topics/email/#mail-managers

**Comment by finnbar** [comment]
Proposed fix applied in fixes branch.
